export const MENUITEMS = [
  {
    menutitle: "لوحة التحكم",
    Items: [
      {
        path: "/dashboard/pages/dashboard",
        icon: "ti-bar-chart",
        type: "link",
        active: false,
        selected: false,
        title: "الرئيسية",
      },
      {
        path: "/dashboard/pages/users",
        icon: "ti-user",
        type: "link",
        active: false,
        selected: false,
        title: "العملاء",
      },
      {
        path: "/dashboard/pages/info-update-requests",
        icon: "ti-user",
        type: "link",
        active: false,
        selected: false,
        title: "طلبات التحديث",
      },

      {
        path: "/dashboard/pages/acc-users",
        icon: "ti-user",
        type: "link",
        active: false,
        selected: false,
        title: "المبيعات",
      },
      {
        path: "/dashboard/pages/packages",
        icon: "ti-package",
        type: "link",
        active: false,
        selected: false,
        title: "الباقات",
      },
      {
        path: "/dashboard/pages/purchases",
        icon: "ti-money",
        type: "link",
        active: false,
        selected: false,
        title: "عمليات الشراء",
      },
      {
        path: "/dashboard/pages/purchase-feedback",
        icon: "ti-star",
        type: "link",
        active: false,
        selected: false,
        title: "التقييمات",
      },
      {
        path: "/dashboard/pages/delayed-orders",
        icon: "ti-alarm-clock",
        type: "link",
        active: false,
        selected: false,
        title: "طلبات متأخرة",
      },
      {
        path: "/dashboard/pages/sales-operations",
        icon: "ti-check-box",
        type: "link",
        active: false,
        selected: false,
        title: "عمليات البيع",
      },
      {
        path: "/dashboard/pages/saleRecords",
        icon: "ti-loop",
        type: "link",
        active: false,
        selected: false,
        title: "الطلبات المستلمة",
      },
      {
        path: "/dashboard/pages/sales",
        icon: "ti-money",
        type: "link",
        active: false,
        selected: false,
        title: "سجل البيع",
      },
      {
        path: "/dashboard/pages/wallets",
        icon: "ti-wallet",
        type: "link",
        active: false,
        selected: false,
        title: "المحافظ",
      },
      {
        path: "/dashboard/pages/transactions-requests",
        icon: "ti-loop",
        type: "link",
        active: false,
        selected: false,
        title: "طلبات التحويل",
      },
      {
        path: "/dashboard/pages/records",
        icon: "ti-loop",
        type: "link",
        active: false,
        selected: false,
        title: " السجلات",
      },
      {
        path: "/dashboard/pages/wallets-transactions",
        icon: "ti-loop",
        type: "link",
        active: false,
        selected: false,
        title: "سجلات التحويل",
      },
      {
        path: "/dashboard/pages/purchasing_pick_process",
        icon: "ti-money",
        type: "link",
        active: false,
        selected: false,
        title: "مبيعات الاستلام",
      },
      {
        path: "/dashboard/pages/wating-list",
        icon: "ti-list",
        type: "link",
        active: false,
        selected: false,
        title: "قائمة الانتظار",
      },
      {
        path: "/dashboard/pages/sales-employees",
        icon: "ti-truck",
        type: "link",
        active: false,
        selected: false,
        title: "موظفو المبيعات",
      },
      // {
      //   path: "/dashboard/pages/accountants",
      //   icon: "ti-lock",
      //   type: "link",
      //   active: false,
      //   selected: false,
      //   title: "المحاسبون",
      // },
      {
        path: "/dashboard/pages/sub-admins",
        icon: "ti-lock",
        type: "link",
        active: false,
        selected: false,
        title: "المشرفون",
      },
      {
        path: "/dashboard/pages/vendor",
        icon: "ti-home",
        type: "link",
        active: false,
        selected: false,
        title: "بيانات الشركة",
      },
      {
        path: "/dashboard/pages/support-messages",
        icon: "ti-comment-alt",
        type: "link",
        active: false,
        selected: false,
        title: "رسائل الدعم",
      },
      {
        path: "/dashboard/pages/notification",
        icon: "ti-comment-alt",
        type: "link",
        active: false,
        selected: false,
        title: " ارسال الاشعارات",
      },
      {
        path: "/dashboard/pages/marketing",
        icon: "ti-announcement",
        type: "link",
        active: false,
        selected: false,
        title: "المسوقين",
      },
      {
        path: "/dashboard/pages/app-settings",
        icon: "ti-mobile",
        type: "link",
        active: false,
        selected: false,
        title: "اعدادات التطبيق",
      },
      {
        path: "/dashboard/pages/contract-form",
        icon: "ti-file",
        type: "link",
        active: false,
        selected: false,
        title: "نموذج العقد",
      },

    ],

  },
  {
    menutitle: "المتجر",
    Items: [
      {
        path: "/dashboard/pages/category",
        icon: "ti-folder",
        type: "link",
        active: false,
        selected: false,
        title: "الأقسام",
      },
      {
        path: "/dashboard/pages/products",
        icon: "ti-package",
        type: "link",
        active: false,
        selected: false,
        title: "المنتجات",
      },
      {
        path: "/dashboard/pages/units",
        icon: "ti-package",
        type: "link",
        active: false,
        selected: false,
        title: "الوحدات",
      },
      {
        path: "/dashboard/pages/countries",
        icon: "ti-package",
        type: "link",
        active: false,
        selected: false,
        title: "الدول ",
      },
      {
        path: "/dashboard/pages/cities",
        icon: "ti-package",
        type: "link",
        active: false,
        selected: false,
        title: "المدن",
      },
      {
        path: "/dashboard/pages/usersStore",
        icon: "ti-package",
        type: "link",
        active: false,
        selected: false,
        title: "عملاء التطبيق",
      },
      {
        path: "/dashboard/pages/sliders",
        icon: "ti-package",
        type: "link",
        active: false,
        selected: false,
        title: " سلايدر الصور",
      },
      {
        path: "/dashboard/pages/addresses",
        icon: "ti-package",
        type: "link",
        active: false,
        selected: false,
        title: "  العناوين",
      },
    ],
  },
];
